name: flight_scanner
description: "A flight scanner app to search for best deals in flights and book them."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^2.19.6

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/login.png
    - assets/icons/signup.png
    - assets/icons/profile-icon-design-free-vector.jpg
    - assets/icons/indonesia.jpg
    - assets/icons/indonesia-2.jpg
    - assets/icons/dubai.jpg